services:
  3proxy:
    image: ghcr.io/tarampampam/3proxy:latest
    container_name: 3proxy
    restart: unless-stopped
    environment:
      - PROXY_LOGIN=evil
      - PROXY_PASSWORD=live
    ports:
      - "3128:3128/tcp"
      - "1080:1080/tcp"
