# yaml-language-server: $schema=https://json.schemastore.org/artifacthub-repo.json
# docs: https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml

repositoryID: 4166fa62-8485-47cb-8512-1ce4880385a4
owners:
  - name: tarampampam
    email: 7326800+tarampampam@users.noreply.github.com
